language: node_js
node_js:
  - "6.9.1"
notifications:
  email:
    recipients:
      - adasq3@gmail.com
    on_success: never
    on_failure: always
after_success:
  # Send coverage data to Coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js